{{- if .Values.sftp.hostKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sftp.hostKeys.ed25519 }}
  ssh_host_ed25519_key: {{ .Values.sftp.hostKeys.ed25519 | b64enc }}
  {{- end }}
  {{- if .Values.sftp.hostKeys.rsa }}
  ssh_host_rsa_key: {{ .Values.sftp.hostKeys.rsa | b64enc }}
  {{- end }}
{{- end }}