apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
data:
  users.conf: |
{{ range $i, $user := .Values.sftp.users }}
    {{ range $j, $dir := $user.dirs }}
    {{ $user.name }}:{{ $user.password }}:{{ $user.uid}}:{{ $user.gid }}:{{ $dir }}
    {{ end }}
{{ end }}
